# Generated by Django 3.1.3 on 2021-01-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='call',
            name='tags',
            field=models.ManyToManyField(blank=True, to='calls.CallTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='call',
            name='teammember',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teammember', verbose_name="Membre d'équipe"),
        ),
    ]
